/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Employee = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'wageRate' : IDL.Float64,
});
export const PayrollEntry = IDL.Record({
  'id' : IDL.Text,
  'tipsEarned' : IDL.Float64,
  'hoursWorked' : IDL.Float64,
  'employeeId' : IDL.Text,
  'isStudent' : IDL.Bool,
  'totalWages' : IDL.Float64,
});

export const idlService = IDL.Service({
  'clearPayrollEntries' : IDL.Func([], [], []),
  'createEmployee' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [], []),
  'createPayrollEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Bool],
      [],
      [],
    ),
  'deleteEmployee' : IDL.Func([IDL.Text], [], []),
  'deletePayrollEntry' : IDL.Func([IDL.Text], [], []),
  'getEmployee' : IDL.Func([IDL.Text], [Employee], ['query']),
  'getPayrollEntriesByEmployee' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PayrollEntry)],
      ['query'],
    ),
  'getPayrollEntry' : IDL.Func([IDL.Text], [PayrollEntry], ['query']),
  'listEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'listPayrollEntries' : IDL.Func([], [IDL.Vec(PayrollEntry)], ['query']),
  'updateEmployee' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [], []),
  'updatePayrollEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Employee = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'wageRate' : IDL.Float64,
  });
  const PayrollEntry = IDL.Record({
    'id' : IDL.Text,
    'tipsEarned' : IDL.Float64,
    'hoursWorked' : IDL.Float64,
    'employeeId' : IDL.Text,
    'isStudent' : IDL.Bool,
    'totalWages' : IDL.Float64,
  });
  
  return IDL.Service({
    'clearPayrollEntries' : IDL.Func([], [], []),
    'createEmployee' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [], []),
    'createPayrollEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Bool],
        [],
        [],
      ),
    'deleteEmployee' : IDL.Func([IDL.Text], [], []),
    'deletePayrollEntry' : IDL.Func([IDL.Text], [], []),
    'getEmployee' : IDL.Func([IDL.Text], [Employee], ['query']),
    'getPayrollEntriesByEmployee' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PayrollEntry)],
        ['query'],
      ),
    'getPayrollEntry' : IDL.Func([IDL.Text], [PayrollEntry], ['query']),
    'listEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'listPayrollEntries' : IDL.Func([], [IDL.Vec(PayrollEntry)], ['query']),
    'updateEmployee' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [], []),
    'updatePayrollEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };