/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Employee {
  'id' : string,
  'name' : string,
  'wageRate' : number,
}
export interface PayPeriod {
  'id' : string,
  'endDate' : string,
  'cashTotal' : number,
  'employeeCount' : bigint,
  'createdAt' : bigint,
  'totalTips' : number,
  '_label' : string,
  'grandTotal' : number,
  'totalWages' : number,
  'overtimeTotal' : number,
  'startDate' : string,
}
export interface PayrollEntry {
  'id' : string,
  'tipsEarned' : number,
  'paymentMethod' : string,
  'fixedSalaryAmount' : number,
  'isFixedSalary' : boolean,
  'hoursWorked' : number,
  'overtimeWageRate' : number,
  'employeeId' : string,
  'overtimePaymentMethod' : string,
  'isStudent' : boolean,
  'totalWages' : number,
  'overtimeTotal' : number,
  'overtimeHours' : number,
}
export interface WeeklyTotals {
  'tipTotal' : number,
  'grandTotal' : number,
  'wageTotal' : number,
  'overtimeTotal' : number,
}
export interface _SERVICE {
  'calculateWeeklyTotals' : ActorMethod<[string], WeeklyTotals>,
  'clearPayrollEntries' : ActorMethod<[string], undefined>,
  'createEmployee' : ActorMethod<[string, string, string, number], undefined>,
  'createPayrollEntry' : ActorMethod<
    [
      string,
      string,
      string,
      number,
      number,
      boolean,
      number,
      number,
      boolean,
      number,
      string,
      string,
    ],
    undefined
  >,
  'deleteEmployee' : ActorMethod<[string, string], undefined>,
  'deletePayrollEntry' : ActorMethod<[string, string], undefined>,
  'getEmployee' : ActorMethod<[string, string], Employee>,
  'getLatestPayPeriod' : ActorMethod<[string], [] | [PayPeriod]>,
  'getPayrollEntriesByEmployee' : ActorMethod<
    [string, string],
    Array<PayrollEntry>
  >,
  'getPayrollEntry' : ActorMethod<[string, string], PayrollEntry>,
  'listEmployees' : ActorMethod<[string], Array<Employee>>,
  'listPayPeriods' : ActorMethod<[string], Array<PayPeriod>>,
  'listPayrollEntries' : ActorMethod<[string], Array<PayrollEntry>>,
  'savePayPeriod' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      number,
      number,
      number,
      number,
      number,
      bigint,
    ],
    undefined
  >,
  'updateEmployee' : ActorMethod<[string, string, string, number], undefined>,
  'updatePayrollEntry' : ActorMethod<
    [
      string,
      string,
      string,
      number,
      number,
      boolean,
      number,
      number,
      boolean,
      number,
      string,
      string,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];