/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Employee {
  'id' : string,
  'name' : string,
  'wageRate' : number,
}
export interface PayrollEntry {
  'id' : string,
  'tipsEarned' : number,
  'hoursWorked' : number,
  'employeeId' : string,
  'isStudent' : boolean,
  'totalWages' : number,
}
export interface _SERVICE {
  'clearPayrollEntries' : ActorMethod<[], undefined>,
  'createEmployee' : ActorMethod<[string, string, number], undefined>,
  'createPayrollEntry' : ActorMethod<
    [string, string, number, number, boolean],
    undefined
  >,
  'deleteEmployee' : ActorMethod<[string], undefined>,
  'deletePayrollEntry' : ActorMethod<[string], undefined>,
  'getEmployee' : ActorMethod<[string], Employee>,
  'getPayrollEntriesByEmployee' : ActorMethod<[string], Array<PayrollEntry>>,
  'getPayrollEntry' : ActorMethod<[string], PayrollEntry>,
  'listEmployees' : ActorMethod<[], Array<Employee>>,
  'listPayrollEntries' : ActorMethod<[], Array<PayrollEntry>>,
  'updateEmployee' : ActorMethod<[string, string, number], undefined>,
  'updatePayrollEntry' : ActorMethod<
    [string, string, number, number, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];