/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const WeeklyTotals = IDL.Record({
  'tipTotal' : IDL.Float64,
  'grandTotal' : IDL.Float64,
  'wageTotal' : IDL.Float64,
  'overtimeTotal' : IDL.Float64,
});
export const Employee = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'wageRate' : IDL.Float64,
});
export const PayPeriod = IDL.Record({
  'id' : IDL.Text,
  'endDate' : IDL.Text,
  'cashTotal' : IDL.Float64,
  'employeeCount' : IDL.Nat,
  'createdAt' : IDL.Int,
  'totalTips' : IDL.Float64,
  '_label' : IDL.Text,
  'grandTotal' : IDL.Float64,
  'totalWages' : IDL.Float64,
  'overtimeTotal' : IDL.Float64,
  'startDate' : IDL.Text,
});
export const PayrollEntry = IDL.Record({
  'id' : IDL.Text,
  'tipsEarned' : IDL.Float64,
  'paymentMethod' : IDL.Text,
  'fixedSalaryAmount' : IDL.Float64,
  'isFixedSalary' : IDL.Bool,
  'hoursWorked' : IDL.Float64,
  'overtimeWageRate' : IDL.Float64,
  'employeeId' : IDL.Text,
  'overtimePaymentMethod' : IDL.Text,
  'isStudent' : IDL.Bool,
  'totalWages' : IDL.Float64,
  'overtimeTotal' : IDL.Float64,
  'overtimeHours' : IDL.Float64,
});

export const idlService = IDL.Service({
  'calculateWeeklyTotals' : IDL.Func([IDL.Text], [WeeklyTotals], ['query']),
  'clearPayrollEntries' : IDL.Func([IDL.Text], [], []),
  'createEmployee' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
      [],
      [],
    ),
  'createPayrollEntry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Bool,
        IDL.Float64,
        IDL.Float64,
        IDL.Bool,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'deleteEmployee' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deletePayrollEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getEmployee' : IDL.Func([IDL.Text, IDL.Text], [Employee], ['query']),
  'getLatestPayPeriod' : IDL.Func([IDL.Text], [IDL.Opt(PayPeriod)], ['query']),
  'getPayrollEntriesByEmployee' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(PayrollEntry)],
      ['query'],
    ),
  'getPayrollEntry' : IDL.Func([IDL.Text, IDL.Text], [PayrollEntry], ['query']),
  'listEmployees' : IDL.Func([IDL.Text], [IDL.Vec(Employee)], ['query']),
  'listPayPeriods' : IDL.Func([IDL.Text], [IDL.Vec(PayPeriod)], ['query']),
  'listPayrollEntries' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PayrollEntry)],
      ['query'],
    ),
  'savePayPeriod' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
      ],
      [],
      [],
    ),
  'updateEmployee' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
      [],
      [],
    ),
  'updatePayrollEntry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Bool,
        IDL.Float64,
        IDL.Float64,
        IDL.Bool,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const WeeklyTotals = IDL.Record({
    'tipTotal' : IDL.Float64,
    'grandTotal' : IDL.Float64,
    'wageTotal' : IDL.Float64,
    'overtimeTotal' : IDL.Float64,
  });
  const Employee = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'wageRate' : IDL.Float64,
  });
  const PayPeriod = IDL.Record({
    'id' : IDL.Text,
    'endDate' : IDL.Text,
    'cashTotal' : IDL.Float64,
    'employeeCount' : IDL.Nat,
    'createdAt' : IDL.Int,
    'totalTips' : IDL.Float64,
    '_label' : IDL.Text,
    'grandTotal' : IDL.Float64,
    'totalWages' : IDL.Float64,
    'overtimeTotal' : IDL.Float64,
    'startDate' : IDL.Text,
  });
  const PayrollEntry = IDL.Record({
    'id' : IDL.Text,
    'tipsEarned' : IDL.Float64,
    'paymentMethod' : IDL.Text,
    'fixedSalaryAmount' : IDL.Float64,
    'isFixedSalary' : IDL.Bool,
    'hoursWorked' : IDL.Float64,
    'overtimeWageRate' : IDL.Float64,
    'employeeId' : IDL.Text,
    'overtimePaymentMethod' : IDL.Text,
    'isStudent' : IDL.Bool,
    'totalWages' : IDL.Float64,
    'overtimeTotal' : IDL.Float64,
    'overtimeHours' : IDL.Float64,
  });
  
  return IDL.Service({
    'calculateWeeklyTotals' : IDL.Func([IDL.Text], [WeeklyTotals], ['query']),
    'clearPayrollEntries' : IDL.Func([IDL.Text], [], []),
    'createEmployee' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
        [],
        [],
      ),
    'createPayrollEntry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Bool,
          IDL.Float64,
          IDL.Float64,
          IDL.Bool,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'deleteEmployee' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deletePayrollEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getEmployee' : IDL.Func([IDL.Text, IDL.Text], [Employee], ['query']),
    'getLatestPayPeriod' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PayPeriod)],
        ['query'],
      ),
    'getPayrollEntriesByEmployee' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(PayrollEntry)],
        ['query'],
      ),
    'getPayrollEntry' : IDL.Func(
        [IDL.Text, IDL.Text],
        [PayrollEntry],
        ['query'],
      ),
    'listEmployees' : IDL.Func([IDL.Text], [IDL.Vec(Employee)], ['query']),
    'listPayPeriods' : IDL.Func([IDL.Text], [IDL.Vec(PayPeriod)], ['query']),
    'listPayrollEntries' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PayrollEntry)],
        ['query'],
      ),
    'savePayPeriod' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
        ],
        [],
        [],
      ),
    'updateEmployee' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
        [],
        [],
      ),
    'updatePayrollEntry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Bool,
          IDL.Float64,
          IDL.Float64,
          IDL.Bool,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };