/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PayrollEntry {
    id: string;
    tipsEarned: number;
    hoursWorked: number;
    employeeId: string;
    isStudent: boolean;
    totalWages: number;
}
export interface Employee {
    id: string;
    name: string;
    wageRate: number;
}
export interface backendInterface {
    clearPayrollEntries(): Promise<void>;
    createEmployee(id: string, name: string, wageRate: number): Promise<void>;
    createPayrollEntry(id: string, employeeId: string, hoursWorked: number, tipsEarned: number, isStudent: boolean): Promise<void>;
    deleteEmployee(id: string): Promise<void>;
    deletePayrollEntry(id: string): Promise<void>;
    getEmployee(id: string): Promise<Employee>;
    getPayrollEntriesByEmployee(employeeId: string): Promise<Array<PayrollEntry>>;
    getPayrollEntry(id: string): Promise<PayrollEntry>;
    listEmployees(): Promise<Array<Employee>>;
    listPayrollEntries(): Promise<Array<PayrollEntry>>;
    updateEmployee(id: string, name: string, wageRate: number): Promise<void>;
    updatePayrollEntry(id: string, employeeId: string, hoursWorked: number, tipsEarned: number, isStudent: boolean): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async clearPayrollEntries(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearPayrollEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearPayrollEntries();
            return result;
        }
    }
    async createEmployee(arg0: string, arg1: string, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createEmployee(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEmployee(arg0, arg1, arg2);
            return result;
        }
    }
    async createPayrollEntry(arg0: string, arg1: string, arg2: number, arg3: number, arg4: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPayrollEntry(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPayrollEntry(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async deleteEmployee(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEmployee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEmployee(arg0);
            return result;
        }
    }
    async deletePayrollEntry(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePayrollEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePayrollEntry(arg0);
            return result;
        }
    }
    async getEmployee(arg0: string): Promise<Employee> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployee(arg0);
            return result;
        }
    }
    async getPayrollEntriesByEmployee(arg0: string): Promise<Array<PayrollEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayrollEntriesByEmployee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayrollEntriesByEmployee(arg0);
            return result;
        }
    }
    async getPayrollEntry(arg0: string): Promise<PayrollEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayrollEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayrollEntry(arg0);
            return result;
        }
    }
    async listEmployees(): Promise<Array<Employee>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEmployees();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEmployees();
            return result;
        }
    }
    async listPayrollEntries(): Promise<Array<PayrollEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPayrollEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPayrollEntries();
            return result;
        }
    }
    async updateEmployee(arg0: string, arg1: string, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmployee(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmployee(arg0, arg1, arg2);
            return result;
        }
    }
    async updatePayrollEntry(arg0: string, arg1: string, arg2: number, arg3: number, arg4: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePayrollEntry(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePayrollEntry(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
