/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Employee {
    id: string;
    name: string;
    wageRate: number;
}
export interface PayrollEntry {
    id: string;
    tipsEarned: number;
    paymentMethod: string;
    fixedSalaryAmount: number;
    isFixedSalary: boolean;
    hoursWorked: number;
    overtimeWageRate: number;
    employeeId: string;
    overtimePaymentMethod: string;
    isStudent: boolean;
    totalWages: number;
    overtimeTotal: number;
    overtimeHours: number;
}
export interface WeeklyTotals {
    tipTotal: number;
    grandTotal: number;
    wageTotal: number;
    overtimeTotal: number;
}
export interface PayPeriod {
    id: string;
    endDate: string;
    cashTotal: number;
    employeeCount: bigint;
    createdAt: bigint;
    totalTips: number;
    _label: string;
    grandTotal: number;
    totalWages: number;
    overtimeTotal: number;
    startDate: string;
}
export interface backendInterface {
    calculateWeeklyTotals(companyId: string): Promise<WeeklyTotals>;
    clearPayrollEntries(companyId: string): Promise<void>;
    createEmployee(companyId: string, id: string, name: string, wageRate: number): Promise<void>;
    createPayrollEntry(companyId: string, id: string, employeeId: string, hoursWorked: number, tipsEarned: number, isStudent: boolean, overtimeHours: number, overtimeWageRate: number, isFixedSalary: boolean, fixedSalaryAmount: number, paymentMethod: string, overtimePaymentMethod: string): Promise<void>;
    deleteEmployee(companyId: string, id: string): Promise<void>;
    deletePayrollEntry(companyId: string, id: string): Promise<void>;
    getEmployee(companyId: string, id: string): Promise<Employee>;
    getLatestPayPeriod(companyId: string): Promise<PayPeriod | null>;
    getPayrollEntriesByEmployee(companyId: string, employeeId: string): Promise<Array<PayrollEntry>>;
    getPayrollEntry(companyId: string, id: string): Promise<PayrollEntry>;
    listEmployees(companyId: string): Promise<Array<Employee>>;
    listPayPeriods(companyId: string): Promise<Array<PayPeriod>>;
    listPayrollEntries(companyId: string): Promise<Array<PayrollEntry>>;
    savePayPeriod(companyId: string, id: string, startDate: string, endDate: string, _label: string, totalWages: number, totalTips: number, overtimeTotal: number, grandTotal: number, cashTotal: number, employeeCount: bigint): Promise<void>;
    updateEmployee(companyId: string, id: string, name: string, wageRate: number): Promise<void>;
    updatePayrollEntry(companyId: string, id: string, employeeId: string, hoursWorked: number, tipsEarned: number, isStudent: boolean, overtimeHours: number, overtimeWageRate: number, isFixedSalary: boolean, fixedSalaryAmount: number, paymentMethod: string, overtimePaymentMethod: string): Promise<void>;
}
import type { PayPeriod as _PayPeriod } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async calculateWeeklyTotals(arg0: string): Promise<WeeklyTotals> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateWeeklyTotals(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateWeeklyTotals(arg0);
            return result;
        }
    }
    async clearPayrollEntries(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearPayrollEntries(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearPayrollEntries(arg0);
            return result;
        }
    }
    async createEmployee(arg0: string, arg1: string, arg2: string, arg3: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createEmployee(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEmployee(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createPayrollEntry(arg0: string, arg1: string, arg2: string, arg3: number, arg4: number, arg5: boolean, arg6: number, arg7: number, arg8: boolean, arg9: number, arg10: string, arg11: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPayrollEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPayrollEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
            return result;
        }
    }
    async deleteEmployee(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEmployee(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEmployee(arg0, arg1);
            return result;
        }
    }
    async deletePayrollEntry(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePayrollEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePayrollEntry(arg0, arg1);
            return result;
        }
    }
    async getEmployee(arg0: string, arg1: string): Promise<Employee> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployee(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployee(arg0, arg1);
            return result;
        }
    }
    async getLatestPayPeriod(arg0: string): Promise<PayPeriod | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestPayPeriod(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestPayPeriod(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPayrollEntriesByEmployee(arg0: string, arg1: string): Promise<Array<PayrollEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayrollEntriesByEmployee(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayrollEntriesByEmployee(arg0, arg1);
            return result;
        }
    }
    async getPayrollEntry(arg0: string, arg1: string): Promise<PayrollEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayrollEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayrollEntry(arg0, arg1);
            return result;
        }
    }
    async listEmployees(arg0: string): Promise<Array<Employee>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEmployees(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEmployees(arg0);
            return result;
        }
    }
    async listPayPeriods(arg0: string): Promise<Array<PayPeriod>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPayPeriods(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPayPeriods(arg0);
            return result;
        }
    }
    async listPayrollEntries(arg0: string): Promise<Array<PayrollEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPayrollEntries(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPayrollEntries(arg0);
            return result;
        }
    }
    async savePayPeriod(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number, arg10: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePayPeriod(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePayPeriod(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
            return result;
        }
    }
    async updateEmployee(arg0: string, arg1: string, arg2: string, arg3: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmployee(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmployee(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updatePayrollEntry(arg0: string, arg1: string, arg2: string, arg3: number, arg4: number, arg5: boolean, arg6: number, arg7: number, arg8: boolean, arg9: number, arg10: string, arg11: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePayrollEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePayrollEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PayPeriod]): PayPeriod | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
